[versions]
activity = "1.9.3"
agp = "8.9.2"
axemojiview = "1.5.2"
androidImageCropper = "4.5.0"
arindicatorview = "2.0.0"
androidSpinkit = "1.4.0"
appcompat = "1.7.0"
colorpickerview = "2.3.0"
compiler = "4.16.0"
constraintlayout = "2.2.0"
converterGson = "2.11.0"
coreKtx = "1.15.0"
coreSplashscreen = "1.0.1"
decorator = "2.1.0"
flexbox = "3.0.0"
#agora-rtc-sdk = "4.2.1"
glide = "4.16.0"
glideTransformations = "4.3.0"
hilt = "2.51.1"
hiltAndroid = "2.52"
hiltCompiler = "2.52"
kotlin = "2.0.20"
kotlinStdlib = "2.0.20"
kotlinxCoroutinesCore = "1.9.0"
ksp = "2.0.20-1.0.25"
legacySupportV4 = "1.0.0"
lifecycleKtx = "2.8.7"
loggingInterceptor = "5.0.0-alpha.14"
material = "1.11.0" # Don't change it
materialCalendarView = "1.9.2"
navigationKtx = "2.8.4"
permissionx = "1.8.1"
picasso = "2.71828"
recyclerviewAnimators = "4.0.2"
retrofit = "2.11.0"
roundedimageview = "2.3.0"
swipemenurecyclerview = "2.1.5"
toasty = "1.5.2"
annotation = "1.6.0"
billingKtx = "7.0.0"
navigationFragmentKtx = "2.8.9"
navigationUiKtx = "2.8.9"

[libraries]
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
android-spinKit = { module = "com.github.ybq:Android-SpinKit", version.ref = "androidSpinkit" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationKtx" }

compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
decorator = { module = "com.rubensousa:decorator", version.ref = "decorator" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-transformations = { module = "jp.wasabeef:glide-transformations", version.ref = "glideTransformations" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-calendar-view = { module = "com.applandeo:material-calendar-view", version.ref = "materialCalendarView" }
recyclerview-animators = { module = "jp.wasabeef:recyclerview-animators", version.ref = "recyclerviewAnimators" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
permissionx = { module = "com.guolindev.permissionx:permissionx", version.ref = "permissionx" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
roundedimageview = { module = "com.makeramen:roundedimageview", version.ref = "roundedimageview" }
swipeMenuRecyclerView = { module = "com.github.aitsuki:SwipeMenuRecyclerView", version.ref = "swipemenurecyclerview" }
toasty = { module = "com.github.GrenderG:Toasty", version.ref = "toasty" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
devtools = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
